[package]
name = "program"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2="0.10"
hex = "0.4"
ratatui = "0.29.0"
crossterm = "0.29.0"
color-eyre="0.6"
rand = "0.9"
serde_json = "1.0"
derive_setters = "0.1.8"

[profile.dev.package.backtrace]
opt-level = 3